apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{DEPLOYMENT_NAME}}
  name: {{SERVICE_NAME}}
spec:
  ports:
    - name: http
      port: {{CONTAINER_PORT}}
      targetPort: {{CONTAINER_PORT}}
    - name: jnlp
      port: 50000
      targetPort: 50000
  selector:
    app: {{DEPLOYMENT_NAME}}
  type: ClusterIP